# General configuration
# Regular expression to rename raw reads (snakemake -c1 rename)
# Use something like https://regex101.com/ for complex regex
# The first group is the sample name, the second group is the read type (R1 or R2)
# Example: From PROJECT_SAMPLE25_S25_R2_001.fastq.gz to SAMPLE25_R2.fastq.gz
READS_REGEX: .+[-|_](.+)_.+_(.+)_.+\.fastq.gz
# Another example: From SampleName_S1_L001_R1_001.fastq.gz to SampleName_R1.fastq.gz
# READS_REGEX: (.+)_.+_.+_(.+)_.+\.fastq.gz

# Trim reads with trim_galore
trim_galore:
  - "--trim-n" #Removes Ns from either side of the read.
  - "--illumina" #Illumina adapter
  # Don't run with --paired neither -j

# Filter reads with sortmerna, into rRNA and non-rRNA
sortmerna:
  - "--fastx" #Output aligned reads into FASTA/FASTQ file
  - "--paired_in" #Flags the paired-end reads as Aligned, when either of them is Aligned.
  - "--out2" #Output paired reads into separate files.
  # We assume that the database is already indexed (check private_config.yaml), modify if not
  #  - "-m 10240" #"Indexing: the amount of memory (in Mbytes) for building the index"

# Reconstruction of rRNA genes with EMIRGE
metarib:
  # Subsampling reads number in each iteration        
  - SAMPLING_NUM : 1000000
  # EMIRGE parameters   
  - EM_PARA : --phred33 -l 151 -i 300 -s 75 -a 64 -n 25
  # BBTOOLS mapping parameters   
  - MAP_PARA : minid=0.96 maxindel=1 minhits=2 idfilter=0.98   
  # BBTOOLS cluster parameters   
  - CLS_PARA : fo=t ow=t c=t mcs=1 e=5 mid=99    
  # Minimium averge coverage in filter process    
  - MIN_COV : 2 
  # Minimium coverge percent in filter process   
  - MIN_PER : 80

# Taxonomic classification of rRNA with CREST4
crest4:
  - "--search_algo blast" # Search algorithm, either `blast` or `vsearch`. Default: `blast`
  - "--search_db silvamod138pr2" # Database to search against. Default: `silvamod138pr2`

# Assembly of non-rRNA reads with Trinity
trinity:
  - "--SS_lib_type RF" # Strand-specific RNA-Seq read orientation
  # There is no need to add --single or seqtype
# Filter non coding RNA contigs with cmsearch (Rfam)
evalue_non_coding_rna: 0.001 # E-value for non-coding RNA search using cmsearch
# Filter mRNA contigs according to their abundance
filter_mRNA_abundance_minimum: 1 # Relative expression in integers

# Pipeline threads and memory specifications
# You can specify the number of threads for each step of the pipeline
threads:
  trim_galore: 7
  sortmerna: 50
  metarib: 50
  quast: 50
  pigz: 50
  trinity: 50
  cmsearch: 50
  bwamem: 50
  samtools: 50
  crest4: 50
  diamond: 50

memory:
  trinity: 500 #
  
# Private configuration
# Sortmerna databases
# SILVA 138.1 SSURef NR99 tax_silva_trunc.fasta
SORTMERNA_SSU_REF_DATABASE: "/data_2/Databases/TotalRNA-Snakemake/sortmerna/SSU/SILVA_138.1_SSURef_NR99_tax_silva_trunc.fasta"
# SILVA 138.1 LSURef NR99 tax_silva_trunc.fasta
SORTMERNA_LSU_REF_DATABASE: "/data_2/Databases/TotalRNA-Snakemake/sortmerna/LSU/SILVA_138.1_LSURef_NR99_tax_silva_trunc.fasta"
# Sortmerna SSU index, automatically generated if not present
SORTMERNA_SSU_DATABASE_INDEX: "/data_2/Databases/TotalRNA-Snakemake/sortmerna/SSU/idx"
# Sortmerna LSU index, automatically generated if not present
SORTMERNA_LSU_DATABASE_INDEX: "/data_2/Databases/TotalRNA-Snakemake/sortmerna/LSU/idx"

# Non coding RNA database
# Rfam v14.9
RFAM_DATABASE: "/data_2/Databases/TotalRNA-Snakemake/rfam/Rfam_v14.9.cm"

# CREST4 database
# rRNA database for taxonomic classification, automatically generated by CREST4 if not present
# 1. silvamod138: SILVA NR SSU Ref v.138
# 2. silvamod_138_manual: Manual curation of Silvamod138
# 3. silvamod138pr2: Manual curation of Silvamod138 and  PR2 v4.13 database for protists
CREST4_DIR: "/data_2/Databases/CREST4_DB/"

# EMIRGE database for rRNA gene reconstruction
EM_REF : "/data_2/Databases/TotalRNA-Snakemake/emirge/SILVA_138.1_SSURef_NR99_tax_silva_trunc.ge1200bp.le2000bp.0.97.fixed.fasta"
# EMIRGE reference index prefix
EM_BT_PREFIX : "/data_2/Databases/TotalRNA-Snakemake/emirge/SILVA_138.1_SSURef_NR99_tax_silva_trunc.ge1200bp.le2000bp.0.97.fixed"

# AnnoTree database (optional)
ANNOTREE :
  DATABASE : "/data_2/Databases/TotalRNA-Snakemake/annotree/annotree.dmnd"
  MAPPING : "/data_2/Databases/TotalRNA-Snakemake/annotree/megan-mapping-annotree-June-2021.db"
# Brite hierachy (optional)
BRITE : "/data_2/Databases/TotalRNA-Snakemake/brite/ko00001.json"